logging:
 level:
  recipeX: debug

s3Properties:
 region: us-east-1
 bucket-name: your-bucket-name
 access-key: your-access-key
 secret-key: your-secret-key
 public-endpoint: https://s3.amazonaws.com/your-public-endpoint
 url-expiration: 5