name: Publish Docker Image

on:
  push:
    branches:
      - main
    paths:
     - 01/ci/version

  workflow_dispatch:
  
jobs:
  docker_build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read Ci file version
        id: ci_version
        run: echo "::set-output name= version::$(cat 01/ci/version)"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/login-action@v4
        with:
          context: 01/Docker/
          push: true 
          tags: raphaeleze/recipeX:${{ steps.get_commit_hash.outputs.commit_hash }}
