name: Test on Develop
run-name: test-to-dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Clean project
      run: |
        cd 01
        mvn clean

  package:
    needs: clean
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: |
        cd 01
        mvn --batch-mode --update-snapshots package

  test:
    needs: package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run Tests
      run: |
        cd 01
        mvn --batch-mode test

  create-pr-main:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Git user identity
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Merge Develop into Main"
        branch: main
        base: dev
        body: "This pull request is automatically created after tests passed on the develop branch."
